### ISSUE TITLE
Option for encrypting output

### ISSUE THREAD

**Issue by jaw187** [continuationlabs/hapi-setup#2]
In order to prevent leaking sensitive information, an option to encrypt the output should be added.

This would also require another option which includes a route for decrypting data.

**Comment by cjihrig** [comment]
To do this, you have to secure the decrypt route. In which case you should have just secured the route that serves up the data.

I think the best way to handle this is to allow the plugin to be assigned to a specific connection/label or auth scheme. I'll implement this.

**Comment by ldesplat** [comment]
This is only part of the solution. You might still want support or developers fully understand what is running but you don't want to leak production credentials such as the application's database credentials...

There should maybe be a way to redact certain configuration fields? I understand that if you really care, you would also obfuscate those fields in the configuration for your application to de-obfuscate no matter how small a security it provides.

**Comment by arb** [comment]
Maybe instead of adding routes attach a server method or something that does this. Then the developer can hide the result behind any mechanism that suites them? Just throwing out another possible implementation?

**Comment by cjihrig** [comment]
I like both @ldesplat and @arb ideas (although maybe just a `plugin.expose` instead of a server method). Allow users to configure what data they want, and let them be in charge of any fancy routes they want to put into prod.

**Comment by arb** [comment]
Yeah I _meant_ `plugin.expose`, not a server method as that would be pointless.

**Comment by arb** [comment]
https://github.com/continuationlabs/hapi-setup/issues/2 trumps this issue and will let you slice and dice the data as you see fit.
